apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: suvedg-booking-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: suvedg-booking-service
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50